
# Sensor driver configuration
fgs_node:
  ros__parameters:
    ticker_interval_sec: 0.1
    face_detect_threshold: 60     # 0..100
    gesture_detect_threshold: 60  # 0..100
    gesture_detect_range: 100     # 0..100 (percent of max distance)

# Perception adapter (BT topics relay) configuration
perception_adapter:
  ros__parameters:
    #face_detected_sound: "my_face.wav"
    face_detected_text: "I see you!"
    min_confidence: 0.6
    face_cooldown_sec: 2.0
    camera_center_x: 320.0
    ticker_interval_sec: 0.1
